on:
  workflow_dispatch:

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: "Go Version"
        run: sudo go version
      - name: "Go Version"
        run: tree /home/runner/work/
      - name: "Go Version"
        run: ls -lah /home/runner/work/
      - name: "Go Env"
        run: sudo go env
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: "Execute Go Program"
        env:
          GO111MODULE: off
          GOPATH: /home/runner/work/voigt/go
        shell: go run {0}
        run: |
          package main

          import "fmt"

          func main() {
              fmt.Println("hello world")
          }
