on:
  workflow_dispatch:

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: "Go Version"
        run: sudo go version
      - name: "Go Env"
        run: sudo go env
      - name: "Execute Go Program"
        env:
          GO111MODULE: off
        shell: go run {0}
        run: |
          package main

          import "fmt"

          func main() {
              fmt.Println("hello world")
          }
